name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}

          script: |
            cd ~/Fework
            git pull origin main

            cd backend

            docker stop fework-api || true
            docker rm fework-api || true

            docker build -t fework-backend .

            docker run -d \
              --name fework-api \
              -p 5001:5001 \
              --env-file .env \
              fework-backend